FROM node:22

COPY node-frontend.supervisord.conf /etc/supervisor/conf.d/

WORKDIR /frontend

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN curl -sL https://deb.nodesource.com/setup_22.x | bash

RUN apt-get install -y nodejs

RUN npm install

EXPOSE 5173

COPY . .