services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
     - 5173:5173
    volumes:
     - ./frontend:/frontend
    # - /frontend/node_modules
    working_dir: /frontend
    command: npm run dev -- --host
    # depends_on:
    # deploy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: uvicorn main:app --host 0.0.0.0 --port 5555 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia



